### ISSUE TITLE
Swift 3 deprecated. Upgrade to 4 or 5 needed.

### ISSUE THREAD

**Issue by jammind** [pravinkumarputta/cordova-plugin-speech#2]
App Store Connect doesn't accept Swift 3 architect anymore. Could you please upgrade the codes?

**Comment by pravinkumarputta** [comment]
Yes. I’ll work on it.

**Comment by jammind** [comment]
Your plugin works like charm by leveraging the native feature of the OS. I am waiting for the Swift 4/5 version to get the app online. Thank you very much:)

**Comment by jammind** [comment]
I managed to publish the app to App Store. It seems your Swift code is up-to-date. It is my project settings problem.
